# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: freakychimp
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: freakychimp
# "service" is the name of this project. This will also be added to your AWS resource names.
service: candidate

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-south-1
  profile: default # <--- USE THE PROFILE

  logs:
    httpApi: true # <--- ADD THIS
  # Uncomment to easily set up a custom domain. Read the docs for more details:
  # https://www.serverless.com/framework/docs/providers/aws/guide/domains
  # domain: api.example.com

functions:
  api:
    handler: src/app.handler
    events:
      - httpApi: "*"
      # - httpApi:
      #     path: /
      #     method: ANY
plugins:
  - serverless-offline
